export const ERR_OBS_EMPTY            = 'Observation is empty';
export const ERR_OBS_DIM              = 'Observation dimensions must be >= 1';
export const ERR_OBS_DIM_MISMATCH     = 'Observation dimensions mismatch';
export const ERR_OBS_ITEM_NOT_FOUND   = 'Observation has no such index';
export const ERR_OBS_LIST_DIM         = 'Observation list dimensions must be >= 1';
export const ERR_OBS_LIST_EMPTY       = 'Observation list is empty';
export const ERR_CLU_NO_CENTRE        = 'Cluster has no centre';
export const ERR_DIV_BY_ZERO          = 'Division by zero';
export const ERR_RAND_INVALID_MIN_MAX = 'min and max cannot be same';
export const ERR_INVALID_K            = 'k must be greater than 1 and less than the size of observations';
